### DISCUSSION TITLE
Redirect uri mismatch in aws amplify

### DISCUSSION THREAD

**Discussion by IzaanAnwar** [nextauthjs/next-auth#11742] [Help]
### Provider type

Google

### Environment

```
 "next": "14.2.5",
  "next-auth": "5.0.0-beta.18",
  "react": "^18.3.1",
  
```

### Reproduction URL

https://github.com/IzaanAnwar/auth-ex/

### Describe the issue

When I am logging in with google, it after the login complete redirects to `https://localhost:3000` instead of my domain.
It works in localhost as well as in vercel deployment but it is giving me this error only in aws amplify.
`error { error: 'redirect_uri_mismatch', error_description: 'Bad Request' }`

### How to reproduce

It's a private repo.. so I can't give access to whole code but try the repo above and deploy on amplify.

### Expected behavior

Redirects to my domain instead of https://localhost:3000

**Comment by aquiseb** [comment]
Any solution to this?

**Comment by rutopio** [comment]
Besides add environment variabel `AUTH_SECRET`, `AUTH_URL` in Amplify settings, you need to add environment variable into `.env.production` before build.

Go to Amplify dashboard > build setting and edit the file like:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install --force
    build:
      commands:
        - env | grep -e AUTH_ >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - .next/cache/**/*
      - .npm/**/*

```

If your environment variable's prefix is `NEXTAUTH_`, replace `AUTH_`.

Reference: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html
