### DISCUSSION TITLE
NextAuth is redirecting me to localhost:3000 after deploying to amplify

### DISCUSSION THREAD

**Discussion by mattmanik** [nextauthjs/next-auth#5957] [Help]
I don't know what went wrong in my deployment. If I do deploy in Vercel the app works fine. But on AWS it is redirecting me to localhost:3000.

I went through similar discussions and applied some suggestions I saw there. Still it is not working as expected. 

This is my build file. 

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
        - echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env

  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*

```

Also have added my environment variables in Amplify console. The variable name is **NEXTAUTH_URL**

**Comment by emimaricic** [comment]
Hello, I know it's been a while but I have the same problem right now, did you manage to fix it?

**Reply by mattmanik** [reply]
Hello, It's fixed after adding NEXT_PUBLIC in my prefix. In AWS, Please make sure you add this env in your yaml file settings and environment variables. Good luck !

**Reply by aphavichitr** [reply]
@emimaricic @emimaricic i'm encountering the same issue, did you guys ever find a solution?

**Reply by mattmanik** [reply]
@aphavichitr Make sure you add NEXT_PUBLIC in prefix of your env variables

**Reply by aphavichitr** [reply]
Adding the NEXT_PUBLIC prefix didn't work for me, what did work is putting the echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env in the build file, but you need to put it before the npm run build or at least that's how it worked for me. I followed this [thread](https://github.com/nextauthjs/next-auth/discussions/2771)

**Reply by dertin** [reply]
```yaml
build:
  commands:
    - npm install
    - env | grep -e NEXTAUTH_URL >> .env.production
    - npm run build
```
