### DISCUSSION TITLE
confused when experimenting next-auth with api-platform pwa

### DISCUSSION THREAD

**Discussion by MarwenTlili** [nextauthjs/next-auth#7010] [Help]
### Question 💬

I salute you everyone, I'm trying to experiment Next-Auth with Api-Platform (official image).

**links provided the framework**  
| URL  | PATH  | lANGUAGE  | DESCRIPTION  |   |
|---|---|---|---|---|
| https://localhost/docs/  |  api/ | PHP  |  The API |
| https://localhost/ | pwa/ | JavaScript  | The Next.js application |
| https://localhost/admin/ | pwa/pages/admin/ | JavaScript  | The Admin |

---
I setup **NextJS** and **NextAuth** inside **pwa** docker container and used this example [https://github.com/nextauthjs/next-auth-example](url)

**The problem is:**

- when I navigate to https://localhost or https://localhost/auth/signin I always see: 

`GET https://localhost/api/auth/session 404`
`[next-auth][error][CLIENT_FETCH_ERROR] `

- http://localhost:3000 not returning any error, but http://localhost:3000/auth/signin is broken (always return Unauthorized 401 even with correct credentials {email, password})

> **Note**: I tried those envs but no luck, and the same for NEXTAUTH_URL_INTERNAL:
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_URL=https://localhost:3000
NEXTAUTH_URL=https://localhost
---
**Question**: how to integrate Next-Auth inside the PWA container and using https://localhost to navigate the front-end app (not http://localhost:3000)

> **Note**:  I tried to setup next-auth in new project (outside of docker) and it works fine even with signin, 

### How to reproduce ☕️

**.env.local**
NODE_ENV=development
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET= `generated using openssl rand -hex 32`

---
**docker-compose.yml**
```
version: "3.4"
services:
  php:
    container_name: issatex-php
    hostname: issatex-php
    build:
      context: ./api
      target: app_php
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy$$
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}

  pwa:
    container_name: issatex-pwa
    hostname: issatex-pwa
    build:
      context: ./pwa
      target: prod
    environment:
      NEXT_PUBLIC_ENTRYPOINT: http://caddy
    ports:
      - "3000:3000"

  caddy:
    container_name: issatex-caddy
    hostname: issatex-caddy
    build:
      context: api/
      target: app_caddy
    depends_on:
      - php
      - pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost}, caddy:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
volumes:
  php_socket:
  caddy_data:
  caddy_config:
  db_data:
```
---
**docker logs issatex-pwa -n 1000 -f**
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /srv/app/.env.local
event - compiled client and server successfully in 5.9s (249 modules)
wait  - compiling /auth/signin (client and server)...
event - compiled client and server successfully in 2.9s (1176 modules)
```

### Contributing 🙌🏽

Yes, I am willing to help answer this question in a PR
