### DISCUSSION TITLE
NextAuth not working in Openshift

### DISCUSSION THREAD

**Discussion by SleeveShirtholes** [nextauthjs/next-auth#9208] [Help]
I have setup NextAuth with Nextjs locally and have everything working flawlessly. I have now put my application up in Openshift and try to login and my application will not forward me to the Okta login page. I keep getting the following error:

```
SIGNIN_OAUTH_ERROR {
error: RPError: outgoing request timed out after 40000ms
at /opt/app-root/src/.next/server/chunks/540.js:40:38639
at async Issuer.discover (/opt/app-root/src/.next/server/chunks/540.js:40:43225)
at async openidClient (/opt/app-root/src/.next/server/chunks/540.js:7:101191)
at async getAuthorizationUrl (/opt/app-root/src/.next/server/chunks/540.js:7:93268)
at async Object.signin (/opt/app-root/src/.next/server/chunks/540.js:31:8710)
at async AuthHandler (/opt/app-root/src/.next/server/chunks/540.js:7:77727)
at async NextAuthRouteHandler (/opt/app-root/src/.next/server/chunks/540.js:31:19986)
at async e.length.t (/opt/app-root/src/.next/server/chunks/540.js:31:21456)
at async /opt/app-root/src/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:39709,
providerId: 'okta'
}
```

I am behind a corporate proxy so I have tried to implement the patches outlined from this [discussion](https://github.com/nextauthjs/next-auth/discussions/3944) with no success. I am completely dumb founded on what the issue is and how I can fix it. I have checked all the settings for NextAuth to ensure that it isn't just a misconfiguration and everything looks right to me. Any help would be appreciated because at this point I am not sure I can use NextAuth and need to either find another solution (haven't found one) or have to write something from scratch.

Here are some details about the app, please ask for more if needed:

package.json
```
{
  "name": "upc-app-node",
  "version": "0.1.0",
  "files": [
    ".next",
    "patches",
    "prisma",
    "public",
    "scripts",
    "src",
    "graphql.config.yml",
    "jest.config.js",
    "jest.setup.ts",
    "next.config.js",
    "next-env.d.ts",
    "package.json",
    "package-lock.json",
    "postcss.config.js",
    "tsconfig.json"
  ],
  "publishConfig": {
    "registry": "https://nexus2.discoverfinancial.com/repository/npm-all/",
    "access": "public"
  },
  "scripts": {
    "dev": "next dev",
    "build": "npm run prisma:generate && next build && patch-package",
    "start": "next start -p 8080",
    "lint": "next lint",
    "migrate": "npx dotenv -e .env.local -- npx prisma migrate dev --name $Name",
    "test": "jest -i",
    "codegen": "graphql-codegen",
    "ci:setup": "npm ci --loglevel verbose",
    "ci:analyze": "next lint",
    "prisma:generate": "npx prisma generate --schema ./prisma/schema.prisma",
    "prisma:migrate:uat": "npx dotenv -e .env.uat -- npx prisma migrate deploy",
    "prisma:seed:uat": "npx dotenv -e .env.uat prisma db seed"
  },
  "prisma": {
    "seed": "npx dotenv -e .env.uat -- ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seeder.ts"
  },
  "dependencies": {
    "@dfs-react-ui/core": "^0.12.4",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@json2csv/plainjs": "^7.0.3",
    "@mui/icons-material": "^5.14.0",
    "@mui/material": "^5.14.3",
    "@mui/x-data-grid": "^6.10.2",
    "@pothos/core": "^3.33.0",
    "@pothos/plugin-errors": "^3.11.1",
    "@pothos/plugin-prisma": "^3.57.0",
    "@prisma/client": "^5.2.0",
    "@types/react": "18.2.12",
    "@types/react-dom": "18.2.5",
    "@whatwg-node/fetch": "^0.9.9",
    "autoprefixer": "10.4.14",
    "cron-parser": "^4.9.0",
    "dotenv-cli": "^7.2.1",
    "eslint": "8.42.0",
    "eslint-config-next": "13.4.6",
    "graphql": "^16.8.0",
    "graphql-scalars": "^1.22.2",
    "graphql-yoga": "^4.0.4",
    "https-proxy-agent": "^5.0.0",
    "ldapts": "^4.2.6",
    "lodash": "^4.17.21",
    "next": "^13.5.3",
    "next-auth": "^4.24.5",
    "nodemailer": "^6.9.3",
    "patch-package": "^8.0.0",
    "postcss": "8.4.24",
    "proxy-agent": "^6.3.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.45.1",
    "react-spinners": "^0.13.8",
    "snowflake-sdk": "^1.9.0",
    "urql": "^4.0.5"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "^5.0.0",
    "@graphql-codegen/typed-document-node": "^5.0.1",
    "@graphql-codegen/typescript": "^4.0.1",
    "@graphql-codegen/typescript-operations": "^4.0.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@types/jest": "^29.5.2",
    "@types/lodash": "^4.14.195",
    "@types/node": "^20.5.4",
    "@types/snowflake-sdk": "^1.6.13",
    "encoding": "^0.1.13",
    "jest": "^29.5.0",
    "jest-canvas-mock": "^2.5.2",
    "jest-environment-jsdom": "^29.5.0",
    "jest-mock-extended": "^3.0.5",
    "prettier": "^3.0.0",
    "prisma": "^5.2.0",
    "ts-jest": "^29.1.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }
}
```

app/api/auth/[...nextauth]

```
import NextAuth from "next-auth";
import { authOptions } from "../../../../utilities/auth/auth";

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };
```

authOptions

```
import type { NextAuthOptions } from "next-auth";
import OktaProvider from "next-auth/providers/okta";
import { UserUtilities } from "../user.utility";
import CustomAdapter from "./adapter";

console.log("Client id: ", process.env.OKTA_CLIENT_ID);
console.log("Secret: ", process.env.OKTA_CLIENT_SECRET);

// Create the auth options to pass to NextAuth
export const authOptions: NextAuthOptions = {
  secret: process.env.NEXTAUTH_SECRET,
  // @ts-ignore
  adapter: CustomAdapter(),
  session: {
    strategy: "database",
  },
  debug: true,
  logger: {
    error(code, metadata) {
      // log.error(code, metadata)
      console.log("Error");
      console.log(code, metadata);
    },
    warn(code) {
      // log.warn(code)
      console.log("Warning");
      console.log(code);
    },
    debug(code, metadata) {
      // log.debug(code, metadata)
      console.log("Debug");
      console.log(code, metadata);
    },
  },
  providers: [
    // Email({
    //     server: {
    //         host: "apprelay.discoverfinancial.com",
    //         port: 25,
    //         // auth: {
    //         //     user: process.env.SMTP_USER,
    //         //     password: process.env.SMTP_PASSWORD
    //         // }
    //     },
    //     from: "no-reply@discover.com",
    // }),
    OktaProvider({
      clientId: process.env.OKTA_CLIENT_ID as string,
      clientSecret: process.env.OKTA_CLIENT_SECRET as string,
      issuer: "https://didentitydev.oktapreview.com",
      wellKnown:
        "https://didentitydev.oktapreview.com/.well-known/openid-configuration",
      httpOptions: {
        timeout: 40000,
      },
    }),
  ],
  callbacks: {
    async session({ session, user }) {
      console.log("We are getting into the callback!");

      // Query to get the users roles
      const { success, data, error } = await UserUtilities.queryLdap({
        searchBy: "email",
        filter: user.email,
      });

      console.log("LDAP: ", data);

      // If we don't successfully get back the ldap details then we throw an error
      if (!success) {
        throw new Error(error);
      }

      // Set this as a blank list
      let roles = [];

      // If the query to ldap is successful then we grab the users roles
      if (success) {
        roles = data[0].roles;
      }

      console.log("Roles: ", roles);

      // Set values on the session to return
      session["user"] = user;
      // @ts-ignore
      session["roles"] = roles;

      return session;
    },
  },
};
```

Openshift env variables with some sensitive data taken out
```
env:
  - name: NEXTAUTH_SECRET
    value: <random_number_generated>
  - name: NEXTAUTH_URL
    value: https://upc-app-node-uatrelease-uat-1.apps.aws-useast1-apps-dev-1.ocpdev.us-east-1.ac.discoverfinancial.com
  - name: OKTA_CLIENT_ID
    value: <confidiential>
  - name: OKTA_CLIENT_SECRET
    value: <confidential>
  - name: OKTA_ISSUER
    value: https://didentitydev.oktapreview.com
  - name: API_URL
    value: https://upc-app-node-uatrelease-uat-1.apps.aws-useast1-apps-dev-1.ocpdev.us-east-1.ac.discoverfinancial.com/api/graphql
  - name: APP_URL
    value: https://upc-app-node-uatrelease-uat-1.apps.aws-useast1-apps-dev-1.ocpdev.us-east-1.ac.discoverfinancial.com
  - name: https_proxy
    value: <corporate_proxy>
  - name: http_proxy
    value: <corporate_proxy>
  - name: no_proxy
    value: .snowflakecomputing.com,*.discoverfinancial.com,.discoverfinancial.com,amazonaws.com
  - name: noproxy
    value: .snowflakecomputing.com,*.discoverfinancial.com,.discoverfinancial.com,amazonaws.com
  - name: NODE_ENV
    value: development
```
