### ISSUE TITLE
nodemailer provider can't be used as middleware

### ISSUE THREAD

**Issue by arslan2012** [nextauthjs/next-auth#10919]
### Provider type

Email

### Environment

```yaml
System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 23.45 GB / 31.27 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    pnpm: 8.15.2 - /usr/bin/pnpm
  npmPackages:
    @auth/unstorage-adapter: ^2.0.0 => 2.1.0 
    next: latest => 14.2.3 
    next-auth: beta => 5.0.0-beta.18 
    react: ^18.2.0 => 18.3.1 
```

### Reproduction URL

https://github.com/arslan2012/nodemailer-test

### Describe the issue

As soon as you add Nodemailer the auth.ts, middleware stops working, throwing below error
```
⨯ Error: The edge runtime does not support Node.js 'stream' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
```
or maybe this error
```
 ⨯ node_modules/.pnpm/nodemailer@6.9.13/node_modules/nodemailer/lib/base64/index.js (56:0) @ <unknown>
 ⨯ Class extends value undefined is not a constructor or null
null
```

disabling middleware or downgrading to next-auth 4 both fixes this issue.
So this bug is next-auth 5 only.

### How to reproduce

add Nodemailer  provider to the auth.ts and enable middleware

### Expected behavior

everything should work fine.
