### ISSUE TITLE
proxy, google oauth, and connection refusal

### ISSUE THREAD

**Issue by mdelapenya** [nextauthjs/next-auth#1366]
**Describe the bug**
NextAuth is not handling the session when the NextJS app is behind a proxy.

**Steps to reproduce**
1. Clone https://github.com/nextauthjs/next-auth-example 
2. Add the following Dockerfile to the cloned repo:

```Dockerfile
FROM node:alpine

RUN mkdir -p /usr/src
WORKDIR /usr/src

# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY ./package*.json ./

# Install dependencies
RUN npm install --production

COPY . /usr/src

RUN npx next telemetry disable
RUN npm run build
EXPOSE 3000
ENTRYPOINT [ "npm", "run", "start" ]
```
3. Add the following docker-compose.yml file next to the Dockerfile, which uses https://github.com/bunkerity/bunkerized-nginx as a web proxy to handle HTTPS:

```yml
---
version: '3'
services:
  proxy:
    image: bunkerity/bunkerized-nginx:1.2.1
    container_name: proxy
    environment:
      - AUTO_LETS_ENCRYPT=no
      - CONTENT_SECURITY_POLICY=default-src https://local.myapp.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.googleusercontent.com https://platform-lookaside.fbsbx.com https://js.stripe.com 'self' 'unsafe-eval' 'unsafe-inline' ; frame-ancestors 'self'; form-action https://accounts.google.com https://*.facebook.com 'self' ; block-all-mixed-content; sandbox allow-forms allow-same-origin allow-scripts; base-uri 'self';
      - GENERATE_SELF_SIGNED_SSL=yes
      - ALLOWED_METHODS=DELETE|GET|OPTIONS|PATCH|POST|PUT
      - BLOCK_ABUSERS=yes
      - BLOCK_PROXIES=yes
      - BLOCK_TOR_EXIT_NODE=yes
      - BLOCK_USER_AGENT=yes
      - NEXTAUTH_URL=https://local.myapp.com
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL_1=/
      - REVERSE_PROXY_HOST_1=http://web:3000
      - REVERSE_PROXY_URL_2=/api/auth
      - REVERSE_PROXY_HOST_2=http://web:3000/api/auth
      - SERVE_FILES=no
      - SERVER_NAME=local.myapp.com
      - USE_BROTLI=yes
      - USE_GZIP=yes
      - USE_MODSECURITY=no
      - USE_PROXY_CACHE=yes
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost:8080 || exit 1"]
      timeout: 10s
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - web
    networks:
      - nextauth
    restart: always
  web:
    build: "."
    container_name: "web"
    environment:
      - NEXTAUTH_SITE=https://local.myapp.com
      - NEXTAUTH_URL=https://local.myapp.com
      - GOOGLE_ID=YOUR_GOOGLE_IS
      - GOOGLE_SECRET=YOUR_GOOGLE_SECRET
    networks:
      - nextauth
    restart: always

networks:
  nextauth:
```
4. Make sure you update your Google ID and secret in the docker-compose file
5. Make sure you add `https://local.myapp.com/api/auth/callback/google` to the Authorised URLs in the OAuth credentials section in your Google Cloud console
6. Add local.domain.example to your /etc/hosts: `127.0.0.1 local.domain.example`
7. Make sure there is nothing running at 80 or 443 ports
8. Start the project with `docker-compose up`
9. Navigate to `https://local.myapp.com` (_Note: in Chrome you maybe need to type "thisisunsafe"_)
10. Login with your Google account. It will work
11. Logout
12. Login again with same or another account

**Expected behavior**
You should be able to login again

**Current behavior**
It's not possible to login again.

**Screenshots or error logs**
If applicable add screenshots or error logs to help explain the problem.

**Additional context**
Verified in Chrome and Firefox, and there is an open discussion #676 with more context.

There is a weird behaviour here: when the proxy is recreated:
```shell
docker-compose stop proxy && docker-compose kill proxy && docker-compose up -d proxy
```
and you browse `local.myapp.com` **in another tab** (so Chrome requires you to type again the 'thisisunsafe' thing) it is possible to login again, and it also could be the case that if the session is still active, you could see yourself logged in. But at the moment you logout, then it's not possible again.

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [ ] Could not find relevant documentation
* [x] Found the example project helpful
* [ ] Did not find the example project helpful

Not sure if this is the right manner to do, but wanted to put attention in the https://github.com/nextauthjs/next-auth/discussions/676 discussion, where we explained an use case where auth is not able to go via proxy, including an example.

Any help there?
