### ISSUE TITLE
It's very painful to test inside a docker container

### ISSUE THREAD

**Issue by ziedHamdi** [nextauthjs/next-auth#3202]
### Description 📓

Hi folks,

I'm trying to locally reproduce my production environment with docker containers running behind a docker nginx server. My issue is that I have to hack the NEXTAUTH_URL variable by putting it to **http://localhost** to login (nginx from the outiside world), then changing it to **http://nginx** (my container name to be seen from the next.js container). 

This is because the call to **/api/auth/session** is using NEXTAUTH_URL but also the provider callback url construction uses this same variable. In production this is not an issue as all calls point to a registred domain (so it can be found by any docker container through DNS), however, localhost doesn't mean the same thing for the different docker containers and I get a (econnrefused 127.0.0.1) from my next server container trying to find the connected user (ttp://localhost/api/auth/session)

It would be useful to have an optional NEXTAUTH_CALLBACK_URL defaulting to the value of NEXTAUTH_URL that can separate those two features.  

### How to reproduce ☕️

This is my local computer testing version of docker-compose.yml :

```
version: "3.9"

services:
  nginx:
    container_name: nginx
    image: 'nginx:0.1'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/cache:/var/cache/nginx
    networks:
      - weally
#    command: tail -f /dev/null
  redis-server:
    container_name: redis-server
    image: 'redis:6.2-alpine'
    networks:
      - weally
#    ports:
#    - "6379:6379"

  mongo-server:
    container_name: mongo-server
    image: mongo:5.0.3
    networks:
      - weally
    ports:
    - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    restart: always

  graphql_server:
    container_name: graphql_server
    image: node:14.17.3-alpine
    networks:
      - weally
    depends_on:
      - mongo-server
      - redis-server
    volumes:
      - type: bind
        source: ../weallyback/
        target: /back
      - type: volume
        source: backnodemodules # name of the volume, see below
        target: /back/node_modules
        volume:
          nocopy: true
    working_dir: /back
    command: yarn start
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  next_server:
    container_name: next_server
    image: node:14.17.3-alpine
    networks:
      - weally
    depends_on:
      - graphql_server
    volumes:
      - type: bind
        source: ../weally.org/
        target: /front
      - type: volume
        source: frontnodemodules # name of the volume, see below
        target: /front/node_modules
        volume:
          nocopy: true
    working_dir: /front
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      - PORT=3000


volumes:
  frontnodemodules:
  backnodemodules:
  mongodb:
  mongodb_config:

networks:
  weally:
    external: false
    name: weally

```

### Contributing 🙌🏽

Yes, I am willing to help implement this feature in a PR
