### ISSUE TITLE
Unable to connect to PostgreSQL database with Prisma Adapter (Docker)

### ISSUE THREAD

**Issue by NorkzYT** [nextauthjs/next-auth#5805]
### Question 💬

I am using Prisma with NextAuth, and I have followed the following documentation to integrate it. I have also dockerized my frontend.
https://next-auth.js.org/adapters/prisma

In the console of my browser I get the following errors.
```
Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error Failed to fetch Object
```

I have the following in my `.env` file.

```
# Database connection string (required).
DATABASE_URL="postgresql://johndoe:randompassword@hostname:port/db?schema=public"

# Providers
GOOGLE_ID=xxx
GOOGLE_SECRET=xxx
GITHUB_ID=xxx
GITHUB_SECRET=xxx

# NextAuth
NEXTAUTH_URL=https://site.domain.com
NEXTAUTH_SECRET=XXX

# Email Sender
EMAIL_SERVER_HOST=XXX
EMAIL_SERVER_PORT=xxx
EMAIL_SERVER_USER=xxx
EMAIL_SERVER_PASSWORD=xxx
EMAIL_FROM=xxx
```

My linux architecture is `aarch64`.

Dependency versions
```json
    "@next-auth/prisma-adapter": "^1.0.5",
    "@prisma/client": "^4.6.1",
    "next": "^12.3.2",
    "next-auth": "^4.16.4",
```

How can I fix this?

### How to reproduce ☕️

I used the following command to use the new schema.
```bash
npx prisma migrate dev
```

The frontend is proxied with Traefik with the `fileConfig.yml` file.
```yml
http:
  routers:

########################################################################################################################################################################

#name routing
namer:
  entryPoints:
    - https
  rule: "Host(`sub.domain.com`)"
  service: name
  middlewares:
    - "securityHeaders"

  ## SERVICES ##
  services:
    # name service
    name:
      loadbalancer:
        servers:
          - url: http://HOSTNAME:PORT

    ########################################################################################################################################################################

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    gzip:
      compress: {}

    ########################################################################################################################################################################

    traefik-real-ip:
      plugin:
        traefik-real-ip:
          excludednets: 1.1.1.1/24

```

The files I used are listed below.

`Dockerfile`
```dockerfile
# We don't want to start from scratch.
# That is why we tell node here to use the current node image as base.
FROM node:16

# ---- Dependencies ----
# Use changes to package.json to force Docker not to use the cache
# when we change our application's nodejs dependencies:
ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/

# From here we load our application's code in, therefore the previous docker
# "layer" thats been cached will be used if possible.
WORKDIR /opt/app
ADD . /opt/app

# Generate prisma client
RUN npx prisma generate

# # Build the app
RUN npm run build

# Expose the port the app runs.
EXPOSE 8080
EXPOSE 8081

# Start the app
CMD [ "npm", "start", "--", "--port", "1442" ]
```
`docker-compose.yml` FrontEnd file

```.yml
version: '3.8'
services:

  proxy:
    image: norkz/proxy:1.0
    container_name: proxy
    hostname: proxy
    #tty: true
    ports:
     - 3502:8080  # Web interface
     - 5555:8081  # Prisma Studio
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
```

`PostgreSQL` docker compose file
```.yml
version: '3.8'
services:

  backend-postgresql:
    image: postgres:15
    container_name: backend-postgresql
    hostname: backend-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backend
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /mnt/appdata/backend/backend-postgres/data:/var/lib/postgresql/data # Where postgresql.conf is located.
     # - /mnt/appdata/backend/backend-postgres/data/postgresql.conf:/etc/postgresql/postgresql.conf # Custom postgresql.conf file.
     # - /mnt/appdata/backend/backend-postgres/config:/etc/postgresql # Example of postgresql.conf 
    ports:
      - 3501:5432    
   # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  proxy:
    driver: bridge
    external: true
```

`schema.prisma` file
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?
  user              User    @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
}
```

`[...nextauth].js` file
```js
import NextAuth from 'next-auth';
import EmailProvider from 'next-auth/providers/email';
import GithubProvider from 'next-auth/providers/github';
import GoogleProvider from 'next-auth/providers/google';
import {PrismaAdapter} from '@next-auth/prisma-adapter';
import {prisma} from '../../../server/db/client';
import nodemailer from 'nodemailer';
import Handlebars from 'handlebars';
import {readFileSync} from 'fs';
import path from 'path';

// Email sender
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_SERVER_HOST,
  port: process.env.EMAIL_SERVER_PORT,
  auth: {
    user: process.env.EMAIL_SERVER_USER,
    pass: process.env.EMAIL_SERVER_PASSWORD,
  },
  secure: true,
});

const emailsDir = path.resolve(process.cwd(), 'emails');

const sendVerificationRequest = ({identifier, url}) => {
  const emailFile = readFileSync(path.join(emailsDir, 'confirm-email.html'), {
    encoding: 'utf8',
  });
  const emailTemplate = Handlebars.compile(emailFile);
  transporter.sendMail({
    from: `"✨ Hello" ${process.env.EMAIL_FROM}`,
    to: identifier,
    subject: 'Your sign-in link for Hello',
    html: emailTemplate({
      base_url: process.env.NEXTAUTH_URL,
      signin_url: url,
      email: identifier,
    }),
  });
};

const sendWelcomeEmail = async ({user}) => {
  const {email} = user;

  try {
    const emailFile = readFileSync(path.join(emailsDir, 'welcome.html'), {
      encoding: 'utf8',
    });
    const emailTemplate = Handlebars.compile(emailFile);
    await transporter.sendMail({
      from: `"✨ Hello" ${process.env.EMAIL_FROM}`,
      to: email,
      subject: 'Welcome to Hello! 🎉',
      html: emailTemplate({
        base_url: process.env.NEXTAUTH_URL,
        support_email: 'email@gmail.com',
      }),
    });
  } catch (error) {
    console.log(`❌ Unable to send welcome email to user (${email})`);
  }
};

export default NextAuth({
  pages: {
    //  Unbranded authentication pages for handling Sign in, Sign out, Email Verification and displaying error messages.
    signIn: '/dashboard',
    signOut: '/login',
    error: '/404', // Error code passed in query string as ?error=
    // verifyRequest: '/', // (used for check email message)
    // newUser: '/auth/new-user', // New users will be directed here on first sign in (leave the property out if not of interest)
  },
  providers: [
    EmailProvider({
      maxAge: 10 * 60,
      sendVerificationRequest,
    }),
    GithubProvider({
      clientId: process.env.GITHUB_ID,
      clientSecret: process.env.GITHUB_SECRET,
    }),
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_SECRET,
    }),
  ],
  secret: process.env.NEXTAUTH_SECRET,
  adapter: PrismaAdapter(prisma),
  events: {createUser: sendWelcomeEmail},
});

```

`prismadb.ts` file

```ts
import { PrismaClient } from '@prisma/client';

declare global {
  var prisma: PrismaClient | undefined
}

const client = globalThis.prisma || new PrismaClient()
if (process.env.NODE_ENV !== "production") globalThis.prisma = client

export default client
```

I have a custom Github, and Google Auth buttons in the following file below.
```js
  // Google Handler function
  async function handleGoogleSignin() {
    signIn('google', {callbackUrl: 'https://site.domain.com'});
  }

  // Github Login
  async function handleGithubSignin() {
    signIn('github', {callbackUrl: 'https://site.domain.com'});
  }

                        <div className="col-lg-4 col-md-4 col-sm-12">
                          <button onClick={handleGoogleSignin}>
                            <a href="#" className="default-btn mb-30">
                              <i className="bx bxl-google"></i> Google
                            </a>
                          </button>
                        </div>

                        <div className="col-lg-4 col-md-4 col-sm-12">
                          <button onClick={handleGithubSignin}>
                            <a href="#" className="default-btn mb-30">
                              <i className="bx bxl-github"></i> Github
                            </a>
                          </button>
                        </div>
```

For my protected page I have the following inside a `.js` file.
```js
import {getSession} from 'next-auth/react';

export async function getServerSideProps(context) {
  // Check if user is authenticated
  const session = await getSession(context);

  // If not, redirect to the homepage
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
  }
  // If authenticated, return the user object [here we can also return the user's roles].
}
```

### Contributing 🙌🏽

No, I am afraid I cannot help regarding this
