### ISSUE TITLE
Google sign-in from www returns error

### ISSUE THREAD

**Issue by guiaramos** [nextauthjs/next-auth#679]
**Your question**
When I access the website from the cannonical URL the google signin works perfectly.
When I access the website using www the URL return error

To reproduce that you can access our project:
-> google signin does not work => https://www.snuper.io/login
-> google signin works well => https://snuper.io/login

***The settings on google:***
_I tried to add www to the callbackUrl and on Google callback URI list_
![Screen Shot 2020-09-16 at 11 20 23 AM](https://user-images.githubusercontent.com/49703106/93284888-a03ffc80-f80e-11ea-9100-4ddd3963446a.png)

***The error log:***
![Screen Shot 2020-09-16 at 11 21 41 AM](https://user-images.githubusercontent.com/49703106/93284975-cebdd780-f80e-11ea-90d2-f70eeb8831e5.png)

Does anyone had the same issue or now how I can handle this?

**What are you trying to do**
Trying to signin with google oauth

**Feedback**
*Documentation refers to searching through [online documentation](https://next-auth.js.org), code comments and issue history. The example project refers to [next-auth-example](https://github.com/iaincollins/next-auth-example).*

* [x] Found the documentation helpful
* [ ] Found documentation but was incomplete
* [x] Could not find relevant documentation
* [ ] Found the example project helpful
* [x] Did not find the example project helpful

**Comment by guiaramos** [comment]
Well, to fix this issue was a bit complex...

you need to redirect you naked url to www... there are many ways to do that, you [definetly can't](https://news.constellix.com/http-redirects-with-dns-and-why-https-redirects-are-so-ing-hard/) do on DNS and should use proxy for that


**In my case, I am using Kubernetes (GKE) and had to do the following:**
1- Install Helm
2- Install ingress-ngnix
3- Install cert-manager
4- Configure lets encrypt

I need to pass the following annotations:
```yaml    
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
```

and add the hosts as following:
```yaml
  tls:
    - hosts:
        - example.com
        - www.example.com
      secretName: example-tls
```

now its working well
